# Nixpacks configuration for AgileFlow monorepo
[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build:backend']

[start]
cmd = 'npm run start:backend'

[variables]
NODE_ENV = 'production'
