# Railway deployment configuration
version: 2

services:
  backend:
    source: ./backend
    build:
      commands:
        - npm install
        - npm run build
    start:
      command: npm run start:prod
    healthcheck:
      path: /api/health
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      NODE_ENV: production
      PORT: $PORT
