# Railway configuration for AgileFlow monorepo backend deployment

[build]
builder = "NIXPACKS"
buildCommand = "npm run build:backend"

[deploy]
startCommand = "npm run start:backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Force Railway to use npm install instead of npm ci for workspaces
[variables]
NODE_ENV = "production"
NIXPACKS_NO_CACHE = "1"
