# Railway configuration for AgileFlow monorepo backend deployment

[build]
builder = "NIXPACKS"
buildCommand = "npm run build:backend"

[deploy]
startCommand = "npm run start:backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
