# Force Railway to use Nixpacks instead of Docker
[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'bash start.sh'

[variables]
NODE_ENV = 'production'
